// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Online_Store___Final_Project.Data.Models
{
    [Table("categories")]
    public partial class Category
    {
        public Category()
        {
            Items = new HashSet<Item>();
        }

        [Key]
        [Column("categoryId")]
        public int CategoryId { get; set; }
        [Required]
        [Column("categoryName")]
        [StringLength(100)]
        public string CategoryName { get; set; }
        [Required]
        [Column("categoryDescription", TypeName = "mediumtext")]
        public string CategoryDescription { get; set; }
        [Required]
        [Column("categoryImage")]
        [StringLength(100)]
        public string CategoryImage { get; set; }

        [InverseProperty(nameof(Item.Category))]
        public virtual ICollection<Item> Items { get; set; }
    }
}