// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Online_Store___Final_Project.Data.Models
{
    [Table("items")]
    [Index(nameof(CategoryId), Name = "fk_items_categories_idx")]
    public partial class Item
    {
        public Item()
        {
            Orderitems = new HashSet<Orderitem>();
        }

        [Key]
        [Column("itemId")]
        public int ItemId { get; set; }
        [Required]
        [Column("itemName")]
        [StringLength(100)]
        public string ItemName { get; set; }
        [Required]
        [Column("itemDescription", TypeName = "mediumtext")]
        public string ItemDescription { get; set; }
        [Column("itemCost")]
        public int ItemCost { get; set; }
        [Required]
        [Column("itemImage")]
        [StringLength(100)]
        public string ItemImage { get; set; }
        [Column("categoryId")]
        public int CategoryId { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty("Items")]
        public virtual Category Category { get; set; }
        [InverseProperty(nameof(Orderitem.Item))]
        public virtual ICollection<Orderitem> Orderitems { get; set; }
    }
}