// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Online_Store___Final_Project.Data.Models
{
    [Table("orders")]
    [Index(nameof(UserAddressId), Name = "fk_orders_userAddresses1_idx")]
    [Index(nameof(UserId), Name = "fk_orders_users1_idx")]
    public partial class Order
    {
        [Key]
        [Column("orderId")]
        public int OrderId { get; set; }
        [Column("orderDate", TypeName = "datetime")]
        public DateTime OrderDate { get; set; }
        [Column("userId")]
        public int UserId { get; set; }
        [Column("userAddressId")]
        public int UserAddressId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("Orders")]
        public virtual User User { get; set; }
        [ForeignKey(nameof(UserAddressId))]
        [InverseProperty(nameof(Useraddress.Orders))]
        public virtual Useraddress UserAddress { get; set; }
        [InverseProperty("Order")]
        public virtual Orderitem Orderitem { get; set; }
    }
}