// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Online_Store___Final_Project.Data.Models
{
    [Table("orderitems")]
    [Index(nameof(ItemId), Name = "fk_orderItems_items1_idx")]
    public partial class Orderitem
    {
        [Key]
        [Column("orderId")]
        public int OrderId { get; set; }
        [Column("itemId")]
        public int ItemId { get; set; }
        [Column("itemCount")]
        public int? ItemCount { get; set; }

        [ForeignKey(nameof(ItemId))]
        [InverseProperty("Orderitems")]
        public virtual Item Item { get; set; }
        [ForeignKey(nameof(OrderId))]
        [InverseProperty("Orderitem")]
        public virtual Order Order { get; set; }
    }
}