// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Online_Store___Final_Project.Data.Models
{
    [Table("states")]
    public partial class State
    {
        public State()
        {
            Useraddresses = new HashSet<Useraddress>();
        }

        [Key]
        [Column("stateId")]
        public int StateId { get; set; }
        [Required]
        [Column("stateName")]
        [StringLength(50)]
        public string StateName { get; set; }
        [Required]
        [Column("stateCode")]
        [StringLength(10)]
        public string StateCode { get; set; }

        [InverseProperty(nameof(Useraddress.State))]
        public virtual ICollection<Useraddress> Useraddresses { get; set; }
    }
}